// <auto-generated />
using System;
using ClassesStudentsAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClassesStudentsAPI.Migrations
{
    [DbContext(typeof(ClassesStudentsAPIContext))]
    [Migration("20210701095603_Init01")]
    partial class Init01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClassesStudentsAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pohlavi")
                        .HasColumnType("int");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonniCislo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TridaId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("TridaId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("ClassesStudentsAPI.Models.Trida", b =>
                {
                    b.Property<int>("TridaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumUkonceni")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVzniku")
                        .HasColumnType("datetime2");

                    b.Property<string>("KodoveOznaceni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrovenVzdelani")
                        .HasColumnType("int");

                    b.HasKey("TridaId");

                    b.ToTable("Tridy");
                });

            modelBuilder.Entity("ClassesStudentsAPI.Models.Student", b =>
                {
                    b.HasOne("ClassesStudentsAPI.Models.Trida", null)
                        .WithMany()
                        .HasForeignKey("TridaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
